language: c

matrix:
  include:
    - os: osx
      compiler: clang
    - os: linux
      compiler: clang
      env: BUILD=x86_64-linux-gnu CFLAGS=-m64 LDFLAGS=-m64
    - os: linux
      compiler: clang
      env: BUILD=i686-linux-gnu CFLAGS=-m32 LDFLAGS=-m32
    - os: linux
      compiler: gcc
      env: BUILD=x86_64-linux-gnu CFLAGS=-m64 LDFLAGS=-m64
    - os: linux
      compiler: gcc
      env: BUILD=i686-linux-gnu CFLAGS=-m32 LDFLAGS=-m32

addons:
  apt:
    packages:
    - gcc-multilib

script:
    - autoreconf -iv
    - ./configure --enable-Werror
    - DISTCHECK_CONFIGURE_FLAGS="-enable-Werror" make distcheck
    - if [[ $? != 0 ]]; then for i in $(find . -name test-suite.log); do echo $i; cat $i; done; fi;
