sudo: required
language: c
matrix:
  include:
  - os: osx
    compiler: clang
  - os: linux
    compiler: clang
    env: BUILD=x86_64-linux-gnu CFLAGS=-m64 LDFLAGS=-m64
  - os: linux
    compiler: clang
    env: BUILD=i686-linux-gnu CFLAGS=-m32 LDFLAGS=-m32
  - os: linux
    compiler: gcc
    env: BUILD=x86_64-linux-gnu CFLAGS=-m64 LDFLAGS=-m64
  - os: linux
    compiler: gcc
    env: BUILD=i686-linux-gnu CFLAGS=-m32 LDFLAGS=-m32
addons:
  apt:
    packages:
    - gcc-multilib
    - lcov

install:
- cd ${TRAVIS_BUILD_DIR}
# install latest LCOV from GitHub
- git clone https://github.com/linux-test-project/lcov.git
- cd lcov 
- sudo make install
#- sudo make -C lcov-1.11/ install
## install lcov to coveralls conversion + upload tool
- gem install coveralls-lcov
- cd ..
- rm -rf lcov
- "ls -l /usr/local/lib/libg*cov* /opt/local/lib/libg*cov*"

script:
- cd ${TRAVIS_BUILD_DIR}
- autoreconf -iv
- "./configure --enable-Werror"
- make -j 8 && make check > check_output.txt
- DISTCHECK_CONFIGURE_FLAGS="-enable-Werror" make distcheck
- if [[ $? != 0 ]]; then for i in $(find . -name test-suite.log); do echo $i; cat
  $i; done; fi;

after_failure:
- curl -T check_output.txt http://chunk.io/

after_success:
- cd ${TRAVIS_BUILD_DIR}
- test "x$CC" = "xgcc" -o "x$CC" = "xclang" && make code-coverage-capture && coveralls-lcov asn1c-*-coverage.info
#- lcov --directory . --capture --output-file coverage.info # capture coverage info
#- lcov --remove coverage.info 'tests/*' '/usr/*' --output-file coverage.info # filter out system and test code
#- lcov --list coverage.info # debug before upload
#- coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info # uploads to coveralls
env:
  matrix:
    secure: n6Vq07f7DZZVXch4VMR7NCwE3TgskWuNUx/JbuPoaFaVgKD51oafafpSVtEBui3YSJ39kxo23SB1stS+3gjRr8yP4SUnanftw5ELFyIsnCBPQhSGQEXxuo8g9PCxCNfSUb3e4vZzrKQCuHC3LRQcNojYfmIumZJsN5A/o2534ktCJjtkwGY0B5cprVmSjwy5XCcwNNyDEQLGBN5Z5tIHrtp7RZ00hDVSfMj9k7q6hQNlmLE3JA7Jj19wZgwfO/rsW04LzwffyQxluA9xPykWhnGCne9GKCq3JfnMp29+UnPrZqdNbY26RoPrPoD0DkMLnbd1QTJjugE1YhzMHtZtT03RDKU9uk92ayJ0aU1I9ksWZT/Ng76uvv2Z83U6lNtwG94vjNNenpPiZSMe1iwSu0Sttxsy9Uh/0QaKMZ8NixWnCi4bYtq/kAFQWBOIQRR6NhsLI/HCcdQFB14ToWVuk0fUMNFA1eR+TafQurRYeRLuwNoSjNCnEgbEl7pqHeDQf3Rkp1/zrHfrDbsmKXUdbhWmOoB1B5Lz6CXJ4DZeAxDlAmlC0v0QV2Dgk5a3ldpZei53DKV58ChHuTBmLobzdAO58x7M6Y7zrtyFyYKah57RoNeD4oLWi3QDzCjE+IQhkg0CD/1eoMhJ92lLKcRX2hTWD72NEpaBgrtHS4MPDag=
