language: c

os:
  - linux
  - osx

#dist: trusty
#sudo: required
osx_image: xcode8.3

compiler:
  - gcc
  - clang

env:
  matrix:
    -os: linux
       BUILD=x86_64-linux-gnu
       CFLAGS=-m64 LDFLAGS=-m64
    -os: linux
       BUILD=i686-linux-gnu
       CFLAGS=-m32 LDFLAGS=-m32
    -os: osx
       compiler: clang
    -os: osx
       compiler: gcc

 addons:
   apt:
     packages:
     - gcc-multilib

 script:
     - autoreconf -iv
     - ./configure --enable-Werror
     - make -j8
     - make check
     - make distcheck
     compiler: clang

addons:
  apt:
    packages:
    - gcc-multilib

script:
    - autoreconf -iv
    - ./configure --enable-Werror
    - make -j8
    - make check
    - make distcheck
